ALTER TABLE `Order`
    ADD COLUMN `captainAcceptedAt` DATETIME(3) NULL,
    ADD COLUMN `readyForPickupAt` DATETIME(3) NULL,
    MODIFY `status` ENUM(
        'PLACED',
        'CONFIRMED',
        'PACKING',
        'READY_FOR_PICKUP',
        'ASSIGNED_TO_CAPTAIN',
        'OUT_FOR_DELIVERY',
        'DELIVERED',
        'CANCELLED',
        'FAILED',
        'REFUNDED',
        'PENDING',
        'ACCEPTED',
        'CAPTAIN_ASSIGNED',
        'PICKED_UP',
        'REJECTED'
    ) NOT NULL;

UPDATE `Order`
SET `status` = CASE `status`
    WHEN 'PLACED' THEN 'PENDING'
    WHEN 'CONFIRMED' THEN 'ACCEPTED'
    WHEN 'PACKING' THEN 'ACCEPTED'
    WHEN 'ASSIGNED_TO_CAPTAIN' THEN 'CAPTAIN_ASSIGNED'
    WHEN 'OUT_FOR_DELIVERY' THEN 'PICKED_UP'
    WHEN 'FAILED' THEN 'REJECTED'
    WHEN 'REFUNDED' THEN 'CANCELLED'
    ELSE `status`
END;

UPDATE `OrderStatusHistory`
SET `oldStatus` = CASE `oldStatus`
    WHEN 'PLACED' THEN 'PENDING'
    WHEN 'CONFIRMED' THEN 'ACCEPTED'
    WHEN 'PACKING' THEN 'ACCEPTED'
    WHEN 'ASSIGNED_TO_CAPTAIN' THEN 'CAPTAIN_ASSIGNED'
    WHEN 'OUT_FOR_DELIVERY' THEN 'PICKED_UP'
    WHEN 'FAILED' THEN 'REJECTED'
    WHEN 'REFUNDED' THEN 'CANCELLED'
    ELSE `oldStatus`
END;

UPDATE `OrderStatusHistory`
SET `newStatus` = CASE `newStatus`
    WHEN 'PLACED' THEN 'PENDING'
    WHEN 'CONFIRMED' THEN 'ACCEPTED'
    WHEN 'PACKING' THEN 'ACCEPTED'
    WHEN 'ASSIGNED_TO_CAPTAIN' THEN 'CAPTAIN_ASSIGNED'
    WHEN 'OUT_FOR_DELIVERY' THEN 'PICKED_UP'
    WHEN 'FAILED' THEN 'REJECTED'
    WHEN 'REFUNDED' THEN 'CANCELLED'
    ELSE `newStatus`
END;

ALTER TABLE `Order`
    MODIFY `status` ENUM(
        'PENDING',
        'ACCEPTED',
        'CAPTAIN_ASSIGNED',
        'READY_FOR_PICKUP',
        'PICKED_UP',
        'DELIVERED',
        'CANCELLED',
        'REJECTED'
    ) NOT NULL;
