export const queryKeys = {
  authUser: ["auth-user"],
  captainProfile: ["captain-profile"],
  categories: ["categories"],
  shops: (params?: Record<string, unknown>) => ["shops", params],
  shop: (shopId: string) => ["shop", shopId],
  products: (filters?: Record<string, unknown>) => ["products", filters],
  product: (productId: string, shopId?: string) => ["product", productId, shopId],
  cart: (shopId?: string) => ["cart", shopId],
  orders: (params?: Record<string, unknown>) => ["orders", params],
  order: (orderId: string) => ["order", orderId],
  addresses: ["addresses"],
  profile: ["profile"],
  notifications: ["notifications"],
  adminDashboard: ["admin-dashboard"],
  shopSummary: (shopId: string) => ["shop-summary", shopId],
  shopInventory: (shopId: string) => ["shop-inventory", shopId],
  shopOrders: (shopId: string) => ["shop-orders", shopId],
  shopReports: (shopId: string, kind: string) => ["shop-reports", shopId, kind],
  captainOrders: ["captain-orders"],
  adminOrders: ["admin-orders"],
  availableCaptains: ["available-captains"],
  report: (kind: string) => ["report", kind],
} as const;
